import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware to parse large JSON (since we will send base64 data)
  app.use(express.json({ limit: "50mb" }));

  const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });

  // API Route for AI Detection
  app.post("/api/detect", async (req, res) => {
    try {
      const { type, data, mimeType } = req.body;

      if (!data) {
        return res.status(400).json({ error: "No data provided. Please provide text or file data." });
      }

      let contents: any;
      if (type === "text") {
        contents = `Please analyze the following text and determine if it was generated by an AI model.

Text to analyze:
"""
${data}
"""`;
      } else if (type === "image" || type === "audio") {
        contents = {
          parts: [
            {
              text: `Please analyze the provided ${type} and determine if it was created or modified by an AI model. Provide detailed reasoning focusing on anomalies, patterns, or artifacts typical of AI generation.`,
            },
            {
              inlineData: {
                data: data, // Base64 string
                mimeType: mimeType || (type === "image" ? "image/jpeg" : "audio/mpeg"),
              },
            },
          ],
        };
      } else {
        return res.status(400).json({ error: "Invalid type. Must be 'text', 'image', or 'audio'." });
      }

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents,
        config: {
          systemInstruction:
            "You are an expert AI forensic analyst. Your task is to analyze content (text, image, or audio) and determine the likelihood that it was generated by Artificial Intelligence. ALWAYS return a structured JSON response with your conclusion.",
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              isAiGenerated: {
                type: Type.BOOLEAN,
                description: "True if you believe the content is AI generated, false otherwise.",
              },
              confidence: {
                type: Type.NUMBER,
                description: "A confidence score from 0 to 100 indicating how certain you are.",
              },
              reasoning: {
                type: Type.STRING,
                description: "A detailed explanation of the forensic analysis leading to your conclusion.",
              },
            },
            required: ["isAiGenerated", "confidence", "reasoning"],
          },
        },
      });

      const responseText = response.text || "{}";
      const resultData = JSON.parse(responseText);

      res.json(resultData);
    } catch (error) {
      console.error("Error during Gemini API call:", error);
      res.status(500).json({ error: "Failed to analyze content." });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Production: Serve built frontend assets
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
